<div class="spansaw">
            
        </div>
        
		<div class="footer_wrapper">
        <div class="footer">
		
			<div class="left_side">
			
				<div class="footer_logo">
					<span class="footer_logo_all">ALL</span><span class="footer_logo_news">News</span>
				</div>
				<div class="footer_media">
					<ul>
						<a href="#" target="_blank"><li class="facebook"></li></a>
						<a href="#" target="_blank"><li class="twitter"></li></a>
						<a href="#" target="_blank"><li class="googlep"></li></a>
						<a href="#" target="_blank"><li class="youtube"></li></a>
					</ul>
				</div>
				<div class="footer_contact">
					<span class="email_phone">Contact us: name@site.com</span><br />
					<span class="email_phone">Phone: 273 162 43</span>
				</div>
			
			</div>
			
			<div class="middle_side">
				<span class="middle_title">Today 12.09.2013</span><br />
				<a href="#"><img src="images/news/footer/Apple_Ipad.png" alt="news" /></a>
			</div>
			
			<div class="right_side">
				<span class="middle_title">More news</span><br />
					<ul>
						<li><a href="#"><img src="images/news/footer/mic.jpg" alt="news" /></a></li>
						<li><a href="#"><img src="images/news/footer/car.jpg" alt="news" /></a></li>
						<li><a href="#"><img src="images/news/footer/horse.jpg" alt="news" /></a></li>						
					</ul>
					<ul>							
						<li><a href="#"><img src="images/news/footer/hand.jpg" alt="news" /></a></li>
						<li><a href="#"><img src="images/news/footer/music.jpg" alt="news" /></a></li>
						<li><a href="#"><img src="images/news/footer/microphone-and-headphones.jpg" alt="news" /></a></li>	
					</ul>	
			</div>
		
        </div>
        </div>
		
		<div class="links_wrapper">

        <div class="footer_links">	
            <div class="author">
				<span class="autor_text">&copy; 2013 by Viny's Design</span>
			</div>
			<div class="link_details">
				<ul>
					<li><a href="#">LIVE |</a></li>
					<li><a href="#">Sports |</a></li>
					<li><a href="#">Privacy |</a></li>
					<li><a href="#">About us</a></li>
				</ul>
			</div>

            <!-- Button when click go to the top of page-->
            <a href="#" class="bringtop"></a>

        </div>
    </div>