<div class="header">
                <div class="logo">
                    <a href="index.php">
                    <span class="logo_all">ALL</span><span class="logo_news">News</span>
                    </a>
                    <p>An easy way to find out more</p>
                </div>
                <a href="#">
                <span class="news_banner">
                    <!-- image for news banner is in style.css -->
                </span>
                </a>
</div>