			<div class="menu">
                <ul>
                    <li><a href="index.php" class="selected">Home</a></li>
                    <li><a href="news.php">News</a></li>
                    <li><a href="business.php">Business</a></li>
                    <li><a href="technology.php">Technology</a></li>
                    <li><a href="music.php">Music</a></li>
                    <li><a href="sports.php">Sports</a></li>
                </ul>
                
                <form method="post" action="search.php">
                    <input type="text" name="search" id="search" placeholder="Search..." />
                    <input type="image" id="search_button" name="searach_button" value="" />
                </form>
            </div>