<div class="top_bar">
            
            <div class="top_bar_content">
            <span class="reg_log">
                <a href="#" id="signin">Sign In</a> &nbsp; | &nbsp;
                <a href="#" id="register">Register</a>
            </span>
               
            <span class="top_bar_contact">
                <a href="mailto:contact@site.com">Contact us: contact@site.com</a>
            </span>
            </div>
 
</div>